# ArgumentError: wrong number of arguments (1 for 2)
#   from (irb):1:in `calculate_product'
#   from (irb):4
#   from /Users/username/.rvm/rubies/ruby-2.0.0-p353/bin/irb:12:in `<main>'

puts "This error indicates a method named 'calculate_product' was called but with"
puts "the wrong number of arguments passed.  It seems to indicate that 2 arguments"
puts "were expected and only one was passed."
